### ISSUE TITLE
"persists" directory does not included by default

### ISSUE THREAD

**Issue by ComradeLV** [EdJoPaTo/telegram-typescript-bot-template#2]
The "persists" folder is git-ignored, so the user does not clone it with the whole project and need to create it, otherwise will see a FS error: `Error: ENOENT: no such file or directory, open 'persist/sessions.json'`
It's a triffle, but i think needs to be fixed if lib is oriented to basic-level users (according to the readme)
Suggestions:

- Remove persists from .gitignore, instead add persists/sessions.json
- Check if directory exists on startup, if no - mkdir
- Append README by `mkdir persists` command between `npm install` and `npm start`

**Comment by EdJoPaTo** [comment]
That's a good point. I think I would go with the third approach and document that. The user has to make sure to keep persistent data persistent anyway (Backup, …).
That way a user knows what has to be kept and knows what directory to use for other persistent data the bot uses.

For additional explanation: I wouldn't like the first approach as the bot logic should be separated from the individual data used by the bot. The current template only has the session information as persistent data but there might be more persistent data.

**Comment by EdJoPaTo** [comment]
I added that point to the readme in 1723a0201ed67e95f2e11e210b8ec6ba281bb322.
Do you think this is put well for beginners just getting started or is something missing?

**Comment by ComradeLV** [comment]
I think it’s enough and looks well

**Comment by EdJoPaTo** [comment]
Thanks for bringing this up and your time thinking about solutions and filing the issue! :)
