### ISSUE TITLE
bot.use(session()) is now deprecated

### ISSUE THREAD

**Issue by winstxnhdw** [EdJoPaTo/telegram-typescript-bot-template#24]
might want to update this

edit: nvm i thought this was a telegraf repo. i was redirected here from a telegraf package lol. will close this once i get home.

**Comment by EdJoPaTo** [comment]
Even for Telegraf I think session() is fine to use. You just need to know the pitfalls of using it as it is prone to race conditions. Check out https://github.com/telegraf/telegraf/issues/1372 for details here.

Generally I suggest switching to grammY anyway as its documentation is way better. Also it learned from Telegrafs mistakes and improved a bunch of things to be both less buggy and easier to use.

And thanks for taking the time to suggest improvements for projects!

**Comment by winstxnhdw** [comment]
@EdJoPaTo thanks to this repository. i am definitely switching over to grammY later tonight. Telegraf has given me so much issues, especially on TypeScript.
