### ISSUE TITLE
You have to provide the bot-token

### ISSUE THREAD

**Issue by Gustly7** [EdJoPaTo/telegram-typescript-bot-template#56]
How should it work if file .env doesn't exist?
dotenv(); // Load from .env file
const token = env['BOT_TOKEN'];

**Comment by EdJoPaTo** [comment]
Depends on the environment you are starting the bot in.

For Shells like `bash`, `fish` or `zsh` you can do something like this: `export BOT_TOKEN=123:ABC`.

When running with Podman or docker you can specify it with `--env BOT_TOKEN=123:ABC`.

Does this help?

**Comment by Gustly7** [comment]
Nope. Instructions say
npm install
mkdir persist
npm start
No podman, no docker, everything launch locally.

I had to create .env file. But instructions should be updated.

**Comment by EdJoPaTo** [comment]
Thank you for mentioning the outdated README. I didn't notice before. Its updated now: 2d3be8c6ba4dbe4f2045d867b7dda3afaacd57d6
